# Use the official Python image from Docker Hub as the base image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /webapp

# Copy the current directory contents (app.py) into the container at /app
COPY . /webapp

#RUN pip install --no-cache-dir -r requirements.txt

# Install any necessary dependencies (Flask in this case)
RUN pip install --no-cache-dir flask==3.1.0

# Expose port 5000 to the outside world (Flask default port)
EXPOSE 5000

# Set the environment variable inside the container (can be overridden at runtime)
ENV WEBTEXT=World
ENV FLASK_ENV=production
ENV FLASK_APP=webtext-app.py

# Set the command to run the Flask app
CMD ["python", "webtext-app.py", "--debug=False", "--no-reload"]