version: '3'

# Define environment variables for your tasks (optional)
env:
  DOCKER_IMAGE_NAME: webtext-app
  DOCKER_PORT: 8081


tasks:
  # Build the Docker image
  build:
    desc: "Build the Docker image for the Flask app"
    cmds:
      - "docker build -t ${DOCKER_IMAGE_NAME} ."
    silent: true

  # Run the Docker container
  run:
    desc: "Run the Docker container for the Flask app"
    cmds:
      - "docker run -p ${DOCKER_PORT}:5000 -e  WEBTEXT=That_works ${DOCKER_IMAGE_NAME}"
    silent: false
    background: true

  test:
    desc: "test the Docker container for the Flask app"
    cmds:
      - "curl localhost:${DOCKER_PORT}/hello"
    silent: false
    background: true

  lint:
    desc: "lint the Docker container for the Flask app"
    cmds:
      - hadolint Dockerfile
    silent: false
    background: true

  # Stop the running Docker container
  stop:
    desc: "Stop the Docker container"
    cmds:
      - "docker stop ${DOCKER_IMAGE_NAME}"
#      - "docker ps -q --filter 'ancestor=${DOCKER_IMAGE_NAME}' | xargs docker stop"
    silent: false

  # Clean up Docker resources (optional)
  clean:
    desc: "Remove Docker images and containers"
    cmds:
      - "docker rm $(docker ps -aq --filter 'ancestor=${DOCKER_IMAGE_NAME}') || true"
      - "docker rmi ${DOCKER_IMAGE_NAME} || true"
    silent: false

  # Full pipeline (build and run)
  cicd:
    desc: "Build and run the Docker container"
    cmds:
      - "task lint"
      - "task build"
      - "task run"